"""create portfolio foundation tables

Revision ID: 2a3818029a67
Revises: 
Create Date: 2026-07-11 15:39:24.759701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a3818029a67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('cusip', sa.String(length=30), nullable=True),
    sa.Column('isin', sa.String(length=30), nullable=True),
    sa.Column('sedol', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('instrument_type', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cusip'),
    sa.UniqueConstraint('isin'),
    sa.UniqueConstraint('sedol'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'instrument_id', name='uq_position_portfolio_instrument')
    )
    op.create_table('prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'price_date', name='uq_price_instrument_date')
    )
    op.create_index(op.f('ix_prices_instrument_id'), 'prices', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_prices_price_date'), 'prices', ['price_date'], unique=False)
    op.create_table('risk_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'metric_name', 'calculation_date', 'method', name='uq_risk_result_portfolio_metric_date_method')
    )
    op.create_index(op.f('ix_risk_results_calculation_date'), 'risk_results', ['calculation_date'], unique=False)
    op.create_index(op.f('ix_risk_results_metric_name'), 'risk_results', ['metric_name'], unique=False)
    op.create_index(op.f('ix_risk_results_portfolio_id'), 'risk_results', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_results_portfolio_id'), table_name='risk_results')
    op.drop_index(op.f('ix_risk_results_metric_name'), table_name='risk_results')
    op.drop_index(op.f('ix_risk_results_calculation_date'), table_name='risk_results')
    op.drop_table('risk_results')
    op.drop_index(op.f('ix_prices_price_date'), table_name='prices')
    op.drop_index(op.f('ix_prices_instrument_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_table('positions')
    op.drop_table('portfolios')
    op.drop_table('instruments')
    # ### end Alembic commands ###
