"""update instrument table

Revision ID: fcc5e7ec90b1
Revises: 2a3818029a67
Create Date: 2026-07-22 19:11:20.307172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc5e7ec90b1'
down_revision: Union[str, Sequence[str], None] = '2a3818029a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('figi_global', sa.String(length=30), nullable=True))
    op.add_column('instruments', sa.Column('active', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'instruments', ['figi_global'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instruments', type_='unique')
    op.drop_column('instruments', 'active')
    op.drop_column('instruments', 'figi_global')
    # ### end Alembic commands ###
